search_tweets_api_cred:
    key_bearer_token: AAAAAAAAAAAAAAAAAAAAAHmoLwEAAAAA%2BLCESl4Azkc2b%2BfQ1uItzjr4nQk%3DocnYPJaXMOF2uEPd2AunM1YyJ21IOZdBkMhfjbDudRgR1iKYEw
    key: Kw6iVPjMfdoI4j5zU0IEffnZD
    
