FROM python:3.8.10-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt

RUN python -m pip install --upgrade pip

RUN python -m pip install -r requirements.txt

COPY . .

CMD ["python3", "-m", "./main.py"]
